apiVersion: v1
kind: Template
metadata:
  name: flink-image
  annotations:
    description: Flink builder
    tags: flink

parameters:
- name: SOURCE_REPOSITORY_URL
  description: URL of the Git repository Dockerfile
  required: true
  value: https://github.com/eidenworks/container-flink.git
- name: OBJECT_NAME_PREFIX
  description: Name prefix for each object created
  required: true
  value: flink-image 

objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${OBJECT_NAME_PREFIX}

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    strategy:
      type: Docker
    source:
      type: Git
      git:
        uri: ${SOURCE_REPOSITORY_URL}
    output:
      to:
        kind: ImageStream
        name: ${OBJECT_NAME_PREFIX}
    triggers:
    - type: ConfigChange
