kind: Template
apiVersion: v1
template: flink
metadata:
  name: flink
labels:
  app: flinkcluster
objects:

- kind: Service
  apiVersion: v1
  metadata:
    name: ${MASTER_NAME}
    labels:
      name: ${MASTER_NAME}
  spec:
    ports:
      - protocol: TCP
        port: 7077
        targetPort: 7077
    selector:
      name: ${MASTER_NAME}

- kind: Service
  apiVersion: v1
  metadata:
    name: ${MASTER_NAME}-webui
    labels:
      name: ${MASTER_NAME}
  spec:
    ports:
      - protocol: TCP
        port: 8081
        targetPort: 8081
    selector:
      name: ${MASTER_NAME}

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${MASTER_NAME}
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ConfigChange
    replicas: 1
    selector:
      name: ${MASTER_NAME}
    template:
      metadata:
        labels:
          name: ${MASTER_NAME}
      spec:
        containers:
          - name: ${MASTER_NAME}
            image: ${FLINK_IMAGE}
            env:
              - name: FLINK_MASTER_PORT
                value: "7077"
              - name: FLINK_MASTER_WEBUI_PORT
                value: "8081"
            ports:
              - containerPort: 7077
                protocol: TCP
              - containerPort: 8081
                protocol: TCP

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${WORKER_NAME}
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ConfigChange
    replicas: 3
    selector:
      name: ${WORKER_NAME}
    template:
      metadata:
        labels:
          name: ${WORKER_NAME}
      spec:
        containers:
          - name: ${WORKER_NAME}
            image: ${FLINK_IMAGE}
            env:
              - name: FLINK_MASTER_ADDRESS
                value: flink://${MASTER_NAME}:7077
              - name: FLINK_MASTER_UI_ADDRESS
                value: http://${MASTER_NAME}-webui:8081

parameters:
- name: FLINK_IMAGE
  description: Name of the Flink master/worker image
  value: _REPO_/flink-image:latest
- name: MASTER_NAME
  description: master name used as a service name and a selector
  generate: expression
  from: "flink-master-[a-z0-9]{4}"
  required: true
- name: WORKER_NAME
  description: worker name used as a selector
  generate: expression
  from: "flink-worker-[a-z0-9]{4}"
  required: true
